documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

audio:
- changed-files:
  - any-glob-to-any-file: 
    - 'BepInEx/plugins/CustomSounds/bikininjaSounds/**'

cicd:
- changed-files:
  - any-glob-to-any-file: 
    - '.github/**'