name: Build Version and release

on:
  workflow_dispatch:
  push:
    branches: "master"
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          majorList: "major"
          minorList: "minor"
          patchAll: true
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: fix_testPublish
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.nextStrict }}
          tag: ${{ steps.semver.outputs.nextStrict }}
          body: Changelog Contents
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
