name: Build Version and release

on:
  push:
    branches: "master"
  pull_request: 
    
permissions:
  contents: write # to be able to publish a GitHub release
  pull-requests: write # otherwise it fails the success check of semantic-release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: create_tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          default_bump: "patch"
          release_branches: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          release_version: ${{ steps.outputs.create_tag.new_version }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.outputs.create_tag.new_version }}
          make_latest: true