name: Build Version and release

on:
  push:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: master
          dev-branch: dev
      - name: Release
        uses: softprops/action-gh-release@v2.2.0
        with:
          tag_name: ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
          make_latest: true
