name: Build Version and release

on:
  workflow_dispatch:
  push:
    branches: "master"
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          majorList: "major"
          minorList: "minor"
          patchAll: true
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
          noVersionBumpBehavior: "patch"
      - name: truncate current version number
        run: |
          echo "currentStrict=$(${{ steps.semver.outputs.current }} | cut -c2-)" >> GITHUB_ENV

      - name: Release Changelog Builder
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5.0.0
        with:
          ignorePreReleases: "true"
          fromTag: "${{ env.currentStrict }}"
          toTag: "${{ steps.semver.outputs.nextStrict }}"
          outputFile: "CHANGELOG.MD"
          token: ${{ secrets.GITHUB_TOKEN }}
          fetchViaCommits: true
          mode: "HYBRID"
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.nextStrict }}
          tag: ${{ steps.semver.outputs.nextStrict }}
          body: ${{steps.changelog.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          body: ${{steps.changelog.outputs.changelog}}
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          echo "CHANGELOG : ${{steps.changelog.outputs.changelog}}"