name: Build V2 - Version and release on PR

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          release_branches: master
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_prerelease_bump: patch
          tag_prefix: ''
      - name: Release Changelog Builder
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5.0.0
        with:
          # fromTag: ${{ steps.tag_version.outputs.new_version }}
          # toTag: ${{ steps.tag_version.outputs.new_version }}
          outputFile: "CHANGELOG.MD"
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                "categories": [
                  {
                    "title": "## 🎹 Audio",
                    "labels": ["audio", "sound", "sounds"]
                  },
                  {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix", "fixes"]
                  },
                  {
                    "title": "## 🔩 CI/CD (you don't care)",
                    "labels": ["ci"]
                  },
                  {
                    "key": "tests",
                    "title": "## 🧪 Tests",
                    "labels": ["test", "tests"]
                  }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|fixes|perf|refactor|revert|style|test|tests|audio|sound|sounds){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }
      - name: See CHANGELOG
        run: |
          echo "${{steps.changelog.outputs.changelog}}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag_version.outputs.new_version }}
          tag_name: ${{ steps.tag_version.outputs.new_version }}
          body: ${{steps.changelog.outputs.changelog}}
          body_path: CHANGELOG.MD
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          make_latest: true