name: Build Version and release

on:
  push:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Version (dry run)
        id: version_create
        uses: huggingface/semver-release-action@latest
        with:
          dryRun: true
      # - name: Run Changelog CI
      #   uses: saadmk11/changelog-ci@v1.1.2
      #   with:
      #     changelog_filename: CHANGELOG.md
      #     release_version: ${{ steps.outputs.version_create.version }}
      # - name: Create Release
      #   id: version_create
      #   uses: huggingface/semver-release-action@latest
      #   with:
      #     branches: ["master", "dev"]
      #     dryRun: true