name: Publish Package on Thunderstore

on:
  workflow_dispatch:
  release:
    types: released

env:
  description: "Bikininjas Sounds with french people voices and memes"
  mod_name: "BikininjasMonsterSounds"
  website_url: "https://github.com/${{ github.repository }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Get latest release number
        id: latest_release # used to read version in other steps.
        run: |
          echo "release_number=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest -s | jq -r '.tag_name // empty')" >> $GITHUB_ENV

      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: Bikininjas # the thunderstore 'team' to publish under
          description: ${{ env.description }}
          token: ${{ secrets.THUNDERSTORE_SVC_API_KEY }}
          name: ${{ env.mod_name }}
          version: ${{ env.release_number }} # Use the tag as the package version
          community: lethal-company
          deps: |
            BepInEx-BepInExPack@5.4.2100
            Clementinise-CustomSounds@2.3.2
            no00ob-LCSoundTool@1.5.1
          website: "${{ env.website_url }}"
          repo: thunderstore.io
          categories: | # <-- notice this pipe character
              audio
