name: Publish Package on Thunderstore

on:
  release:
  workflow_dispatch:
  push:
    branches: "fix_testPublish"

env:
  description: "Tests Modding Bikininjas Sounds"
  mod_name: "Bikininjas Sounds Test"
  website_url: "https://github.com/${{ github.repository }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get latest release number
        id: latest_release # used to read version in other steps.
        run: |
          echo "release_number=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest -s | jq -r '.tag_name // empty')" >> $GITHUB_ENV
          echo "RELEASE_NUMBER is ${release_number}"
      - name: Get Release Zip
        run: |
          wget https://github.com/${{ github.repository }}/archive/refs/tags/${{ env.release_number }}.zip -O bikininjaSounds-${{ env.release_number }}.zip
      - name: Generate manifest.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "manifest.json"
          json: '{"name":"bikininjaSounds", "version_number":"${{ env.release_number }}", "website_url":"${{ env.website_url }}","description":"${{ env.description }}", "dependencies": ["BepInEx-BepInExPack-5.4.2100", "Clementinise-CustomSounds-2.3.2", "no00ob-LCSoundTool-1.5.1"]}'

      - uses: dhkatz/thunderstore-publish@v1.0.1
        with:
          namespace: Bikininjas # the thunderstore 'team' to publish under
          description: ${{ env.description }}
          token: ${{ secrets.THUNDERSTORE_SVC_API_KEY }}
          name: ${{ env.mod_name }}
          version: ${{ env.release_number }} # Use the tag as the package version
          community: lethal-company
          deps: |
            BepInEx-BepInExPack@5.4.2100
            Clementinise-CustomSounds@2.3.2
            no00ob-LCSoundTool@1.5.1
          website: "${{ env.website_url }}"
          repo: thunderstore.io
          file: ./bikininjaSounds-${{ env.release_number }}.zip
          categories: | # <-- notice this pipe character
              audio